disabled_rules:
  - variable_name
  - line_length
  - force_cast

opt_in_rules:
  - closure_spacing                 # Closure expressions should have a single space inside each brace.
  - empty_count                     # Prefer checking `isEmpty` over comparing `count` to zero
  - explicit_init                   # Explicitly calling .init() should be avoided.
  - overridden_super_call           # Some Overridden methods should always call super.

# Rule Configuration
type_name:
  min_length: 3
  max_length:
    warning: 60
    error: 1000
